name: ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare demo-app
        run: |
          cd pizza-demo
          npm ci --no-audit --no-fund
      - name: Prepare lib
        run: |
          cd lib
          npm ci --no-audit --no-fund
      - name: Prepare root
        run: |
          npm ci --no-audit --no-fund
      - name: Execute tests with defaults
        run: |
          npm run serve-and-test:parallel
      - name: Execute only some tests
        run: |
          npm run serve-and-test:parallel:some
      - name: Execute tests with spec reporter
        run: |
          npm run serve-and-test:parallel:spec
      - name: Execute tests with junit reporter
        run: |
          npm run serve-and-test:parallel:junit
